# This workflow is triggered on pushes to the repository.
name: npm build
on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build

      - name: Build
        uses: elstudio/actions-js-build/build@v2

      - name: Commit
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Build