# This workflow is triggered on pushes to the repository.
name: npm build
on:
  push:
    branches:
      - build

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install
      - uses: actions/checkout@v2
        uses: Adzz/jest_test_action@v1.0.0
        with:
          ref: build
          package-manager: npm
          command: install

  build:
    runs-on: ubunti-latest
    steps:
      - name: Build
      - uses: actions/checkout@v2
        uses: Adzz/jest_test_action@v1.0.0
        with:
          ref: build
          package-manager: npm
          command: build