# This workflow is triggered on pushes to the repository.
name: npm build
on:
  push:
    branches:
      - build

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: build
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm build
      - name: Publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
