# This workflow is triggered on pushes to the repository.
name: npm build
on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: actions/checkout@v2
      - uses: Adzz/yarn_command_action@v1.0.0
        with:
          ref: build
          package-manager: npm
          command: install

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - uses: Adzz/yarn_command_action@v1.0.0
        with:
          ref: build
          package-manager: npm
          command: build
      - run: git push