name: npm build
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - build

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
      - name: Install
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: install
  build:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
      - name: Build
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: build